#pragma once

#include "NativeGameplayTags.h"

namespace PrologueGameplayTags
{
	/** Input Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Sword);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Bow);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InteractStarted);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InteractCompleted);
	
	/** Comma Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Weapon_Sword);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Weapon_Bow);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Attack_Sword);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Attack_Bow);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Dash);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_OverClock);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Skill);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_SmashAttack);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Heal);
	
	/** Comma State Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_SwitchAttack_Sword);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_CancelDisabled);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_CancelEnabled);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_Invincible);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_Dashing);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_OverClock);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_Intro);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_Skill);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_SpeedBoost);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_LowHealth);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_CutScene);
	
	/** Comma Event Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_Sword);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_JustDash);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_SwitchAttackSword);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_HitStop);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_ResetSkillCooldown);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_Immunity);

	/** Comma Cooldown Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Cooldown_Skill);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Cooldown_Heal);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Cooldown_OverClock);

	/** GameplayCue Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_Damaging);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_SmashAttackDamaging);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_SkillDamaging);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_DamagingSound);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_SmashDamagingSound);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_SkillDamagingSound);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_PlayerHit);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_EnemyHit);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_EnemySmashHit);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_EnemySkillHit);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_Stun);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_Heal);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_DashTrail);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_OverClock);

	/** Event Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_AttackHitCheck);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_SecondAttackHitCheck);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_ThirdAttackHitCheck);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_SwitchAttackHitCheck);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_SkillHitCheck);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_BrokenCheck);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_AddSword);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_AddBow);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_SpawnProjectile);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_EnableInput);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_DisableInput);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_NextCombo);

	/** Enemy Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_RangeAttack);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_LaserAttack);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Charge);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Jump);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_BackJump);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_FirstEncounter);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Charge);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Detect);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_CanParry);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Dashed);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_LastCombo);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_LaserHitCheck);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Stun);

	/** Chronos Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_Ability_SummonClock);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_Ability_Skill3);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_Ability_SecondPhase);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_Event_SummonClock);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_Event_AttackHitCheck);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_State_SecondPhase);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chronos_State_Invincible);
	
	/** Shared Tags */
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Cooldown);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitFx);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_IsDead);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_IsAttacking);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_IsMoving);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_IsOutOfToughness);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_NoHitEffect);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_State_Broken);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Cooldown_Attack);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Cooldown_Attack_Laser);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Cooldown_Attack_Ranged);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Cooldown_Attack_Run);
}