#pragma once

#include "NativeGameplayTags.h"

namespace PrologueGameplayTags
{
	//Input Tags
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipHammer);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequippedHammer);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipBow);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequippedBow);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Hammer);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Bow);

	//Comma Tags
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Weapon_Hammer);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Event_Equip_Hammer);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Equip_Hammer);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Unequipped_Hammer);
	
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Attack_Hammer);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_Ability_Attack_Bow);

	//State Tags
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_IsDead);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_IsAttacking);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_IsMoving);

	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_Cancel);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comma_State_CanCancel);

	//Effect Tags
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_Damaging);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_PlayerHit);
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Effect_EnemyHit);

	//Event Tags
	PROLOGUE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Character_AttackHitCheck);
}